// Shared service catalog — used by services.html (browse/book links) and
// book.html (booking wizard). Keep this the single source of truth for
// service names, blurbs, and icons so the two pages never drift apart.
window.SERVICES = [
  { id:"express", name:"Exterior Detail", blurb:"Hand foam wash, wheel & rim cleaning, tire shine, streak-free windows, and spray sealant protection. Starting at $110.", icon:'<path d="M6 24c0-9 8-16 18-16s18 7 18 16" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round"/><path d="M10 30h28M13 36h22" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>', core:true },
  { id:"interior", name:"Interior Detail", blurb:"Complete cabin & trunk vacuum, thorough scrub and sanitize on all plastics, dash & console, leather conditioning, vent cleaning, and streak-free inner glass. Starting at $150.", icon:'<rect x="10" y="10" width="28" height="28" rx="5" stroke="currentColor" stroke-width="2" fill="none"/><path d="M16 24h16M16 30h10" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>', core:true },
  { id:"full", name:"Full Detail", blurb:"The complete Interior + Exterior service, bundled with an automatic $20 discount. Starting at $240.", icon:'<rect x="8" y="16" width="32" height="18" rx="6" stroke="currentColor" stroke-width="2" fill="none"/><circle cx="16" cy="36" r="3.2" stroke="currentColor" stroke-width="2" fill="none"/><circle cx="32" cy="36" r="3.2" stroke="currentColor" stroke-width="2" fill="none"/>', badge:"Best Value", core:true },
  { id:"ceramic", name:"Ceramic Coating", blurb:"Paint-safe decontamination wash followed by a hand-applied ceramic layer for lasting shine.", icon:'<path d="M24 6 34 12v12c0 10-6.5 15.5-10 18-3.5-2.5-10-8-10-18V12Z" stroke="currentColor" stroke-width="2" fill="none" stroke-linejoin="round"/>', addon:true },
  { id:"ceramicwax", name:"Ceramic Wax Upgrade", blurb:"A durable, high-gloss ceramic wax added on top of any wash or detail for extra shine and protection between full ceramic coating services.", price:"+$99", icon:'<path d="M24 6v8M24 34v8M6 24h8M34 24h8M11.5 11.5l5.6 5.6M30.9 30.9l5.6 5.6M36.5 11.5l-5.6 5.6M17.1 30.9l-5.6 5.6" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>', addon:true },
  { id:"headlight", name:"Headlight Restoration", blurb:"Foggy, yellowed headlights buffed and restored back to clear — improves both looks and nighttime visibility.", price:"+$75", icon:'<ellipse cx="18" cy="24" rx="10" ry="12" stroke="currentColor" stroke-width="2" fill="none"/><path d="M32 17h9M34 24h9M32 31h9" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>', addon:true },
  { id:"scratch", name:"Scratch Polishing", blurb:"Light surface scratches and swirl marks polished out by hand for a smoother, more even finish.", icon:'<path d="M9 34 29 14" stroke="currentColor" stroke-width="2" stroke-linecap="round"/><path d="M27 8a10 10 0 1 1-6 18" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round"/>', addon:true },
  { id:"trim", name:"Trim Restoration", blurb:"Faded, sun-bleached plastic trim and bumpers restored back to a deep, even black finish.", icon:'<rect x="8" y="20" width="32" height="8" rx="3" stroke="currentColor" stroke-width="2" fill="none"/><path d="M13 20v8M35 20v8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" opacity="0.5"/>', addon:true },
  { id:"debadge", name:"Debadging", blurb:"Clean removal of unwanted manufacturer badges and emblems for a smoother, more custom look.", icon:'<rect x="14" y="15" width="20" height="14" rx="3" stroke="currentColor" stroke-width="2" fill="none"/><path d="M9 35 39 13" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>', addon:true },
  { id:"bugsap", name:"Bug &amp; Sap Removal", blurb:"Safe, targeted removal of bug splatter, tree sap and road grime from paint and windshield.", icon:'<circle cx="18" cy="18" r="3" fill="currentColor"/><circle cx="30" cy="14" r="2" fill="currentColor"/><circle cx="32" cy="28" r="2.6" fill="currentColor"/><path d="M8 36c8-10 24-10 32 0" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round"/>', addon:true },
  { id:"commercial", name:"Commercial &amp; Fleet", blurb:"Recurring wash plans for business vehicles, fleets and dealerships across Westchester.", icon:'<rect x="6" y="20" width="20" height="12" rx="2" stroke="currentColor" stroke-width="2" fill="none"/><path d="M26 24h8l6 6v2h-14z" stroke="currentColor" stroke-width="2" fill="none" stroke-linejoin="round"/><circle cx="14" cy="34" r="2.6" stroke="currentColor" stroke-width="2" fill="none"/><circle cx="32" cy="34" r="2.6" stroke="currentColor" stroke-width="2" fill="none"/>' }
];
